/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import Control.ControlCliente;;
import Modelo.Conexion;
import Modelo.Render;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.*;
import javax.swing.JButton;

/**
 *
 * @author John Castro
 */
public class vistaFacturaClienteSeleccion extends javax.swing.JFrame {

    /**
     * Creates new form vistaCompra
     */
    private Conexion con;
    private ControlCliente controlC;
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    int id;
    
    public vistaFacturaClienteSeleccion(Conexion con1) {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        con=con1;
        controlC= new ControlCliente(con);
        limpiarTabla();
        listar(); 
    }
    void listar(){    
        modelo=(DefaultTableModel)tablaClientes.getModel();
        /*Se almacena la consulta sql en un string*/
        String sql="SELECT * "+"FROM Cliente";
        try{
            /*se establece coneccion con la base de datos y se le introduce la consulta*/
            cn=con.getConnection();
            st=cn.createStatement();
            rs=st.executeQuery(sql);   
            Object[] Datos= new Object[4]; /*Un array donde se almacenan las filas de la tabla. el tamaño del
            array debe ser el numero de columnas que tenga nuestra consulta*/
            while(rs.next()){
            Datos[0]=rs.getInt("idcliente");/*deben llamarse exactamente igual a como esta en la tabla*/
            Datos[1]=rs.getString("nombrecliente");/*deben llamarse exactamente igual a como esta en la tabla*/
            Datos[2]=rs.getString("direccioncliente");
            Datos[3]=rs.getString("telefonocliente");/*deben llamarse exactamente igual a como esta en la tabla*/
            
            modelo.addRow(Datos);
            }    
        }catch(SQLException e){}
    }
        
    void limpiarTabla(){
        modelo=(DefaultTableModel)tablaClientes.getModel();
        while(modelo.getRowCount()>0)modelo.removeRow(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelProveedorSeleccion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelProveedorTabla = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaClientes = new rojerusan.RSTableMetro();
        AgregarCompraButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelProveedorSeleccion.setBackground(new java.awt.Color(255, 255, 255));
        panelProveedorSeleccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Decker", 0, 36)); // NOI18N
        jLabel1.setText("Clientes");
        panelProveedorSeleccion.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        panelProveedorTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Dirección", "Teléfono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaClientes.setColorBackgoundHead(new java.awt.Color(51, 172, 234));
        tablaClientes.setColorFilasForeground1(new java.awt.Color(51, 51, 51));
        tablaClientes.setColorFilasForeground2(new java.awt.Color(51, 51, 51));
        tablaClientes.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        tablaClientes.setFuenteFilas(new java.awt.Font("Decker", 0, 18)); // NOI18N
        tablaClientes.setFuenteFilasSelect(new java.awt.Font("Decker", 1, 18)); // NOI18N
        tablaClientes.setFuenteHead(new java.awt.Font("Decker", 1, 18)); // NOI18N
        tablaClientes.setGridColor(new java.awt.Color(255, 255, 255));
        tablaClientes.setGrosorBordeFilas(0);
        tablaClientes.setGrosorBordeHead(0);
        tablaClientes.setRowHeight(25);
        tablaClientes.setRowMargin(0);
        tablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaClientes);

        panelProveedorTabla.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 680, 330));

        AgregarCompraButton.setText("Seleccionar");
        AgregarCompraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCompraButtonActionPerformed(evt);
            }
        });
        panelProveedorTabla.add(AgregarCompraButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, -1, -1));

        panelProveedorSeleccion.add(panelProveedorTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 860, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelProveedorSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelProveedorSeleccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void AgregarCompraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCompraButtonActionPerformed
        try{
        vistaFactura.cargarCliente(String.valueOf(tablaClientes.getValueAt(tablaClientes.getSelectedRow(), 0)), String.valueOf(tablaClientes.getValueAt(tablaClientes.getSelectedRow(), 1)),String.valueOf(tablaClientes.getValueAt(tablaClientes.getSelectedRow(), 3)), String.valueOf(tablaClientes.getValueAt(tablaClientes.getSelectedRow(), 2)));
        dispose();
        }catch(Exception e){ JOptionPane.showMessageDialog(null,"Selecciona a un cliente");}
    }//GEN-LAST:event_AgregarCompraButtonActionPerformed

    private void tablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientesMouseClicked
        //En esta parte creo dos variables las cualves van almacenar la posicion en X y Y donde he dado click        
    }//GEN-LAST:event_tablaClientesMouseClicked

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarCompraButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelProveedorSeleccion;
    private javax.swing.JPanel panelProveedorTabla;
    private rojerusan.RSTableMetro tablaClientes;
    // End of variables declaration//GEN-END:variables
}
