/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import Control.ControlCompras;
import Modelo.Conexion;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author John Castro
 */
public class vistaCompra extends javax.swing.JFrame {

    /**
     * Creates new form vistaCompra
     */
    private Conexion con;
    private ControlCompras controlC;
    private int NitProveedor;
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    public static int nitProveedor;
    
    public static void cargarNit(String Nit, String Nombre, String Telefono, String Direccion){
        lblidproveedor.setText(Nit);
        lblproveedornombre.setText(Nombre);
        lbltelefono.setText(Telefono);
        lbldireccion.setText(Direccion);
        nitProveedor = Integer.parseInt(Nit);
    }
    public vistaCompra(Conexion con1) {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        con=con1;
        Date sistFecha=new Date();
        SimpleDateFormat formato= new SimpleDateFormat("dd-MM-yyyy");
        txtFecha.setText(formato.format(sistFecha));
        cargarNumCompra();
    }
    public void listar(){    
        modelo=(DefaultTableModel)tablaCompras.getModel();
        /*Se almacena la consulta sql en un string*/
        String sql="SELECT * FROM Compra";
        try{
            /*se establece coneccion con la base de datos y se le introduce la consulta*/
            cn=con.getConnection();
            st=cn.createStatement();
            rs=st.executeQuery(sql);   
            Object[] Datos= new Object[4]; /*Un array donde se almacenan las filas de la tabla. el tamaño del
            array debe ser el numero de columnas que tenga nuestra consulta*/
            while(rs.next()){
            Datos[0]=rs.getInt("idcompra");/*deben llamarse exactamente igual a como esta en la tabla*/
            Datos[1]=rs.getString("idUsuario");/*deben llamarse exactamente igual a como esta en la tabla*/
            Datos[2]=rs.getString("nitproveedor");
            Datos[3]=rs.getString("totalcompra");/*/*deben llamarse exactamente igual a como esta en la tabla*/
            modelo.addRow(Datos);
            }    
        }catch(SQLException e){}
    }
        
    void limpiarTabla(){
        
        modelo=(DefaultTableModel)tablaCompras.getModel();
        while(modelo.getRowCount()>0)modelo.removeRow(0);
    }
    void cargarNumCompra(){
        String sql="SELECT MAX(idcompra)FROM COMPRA;";
            try{
                /*se establece coneccion con la base de datos y se le introduce la consulta*/
                cn=con.getConnection();
                st=cn.createStatement();
                rs=st.executeQuery(sql);   /*Un array donde se almacenan las filas de la tabla. el tamaño del
                array debe ser el numero de columnas que tenga nuestra consulta*/
                while(rs.next()){
                IdCompraLabel.setText(String.valueOf(rs.getInt(1)+1));
                }    
            }catch(SQLException e){}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCompra = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelCompraCrear = new javax.swing.JPanel();
        lbldireccion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        IdCompraLabel = new javax.swing.JLabel();
        lblproveedornombre = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCompra = new rojerusan.RSTableMetro();
        jLabel6 = new javax.swing.JLabel();
        botonCliente = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblidproveedor = new javax.swing.JLabel();
        lbltelefono = new javax.swing.JLabel();
        panelCompraTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCompras = new rojerusan.RSTableMetro();
        panelCompraMenu = new javax.swing.JPanel();
        botonCrear = new javax.swing.JButton();
        botonVer1 = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        botonVer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelCompra.setBackground(new java.awt.Color(255, 255, 255));
        panelCompra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Decker", 0, 36)); // NOI18N
        jLabel1.setText("Compras");
        panelCompra.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        panelCompraCrear.setBackground(new java.awt.Color(255, 255, 255));
        panelCompraCrear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbldireccion.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        lbldireccion.setText("-");
        panelCompraCrear.add(lbldireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 170, -1));

        jLabel3.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel3.setText("Factura N°:");
        panelCompraCrear.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        txtFecha.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        panelCompraCrear.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 110, 30));

        IdCompraLabel.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        IdCompraLabel.setText("-");
        panelCompraCrear.add(IdCompraLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        lblproveedornombre.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        lblproveedornombre.setText("-");
        panelCompraCrear.add(lblproveedornombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, -1, -1));

        tablaCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "idArticulo", "Descripcion", "Cantidad", "Costo", "Subtotal"
            }
        ));
        tablaCompra.setFuenteHead(new java.awt.Font("Decker", 1, 18)); // NOI18N
        jScrollPane2.setViewportView(tablaCompra);

        panelCompraCrear.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 910, 250));

        jLabel6.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel6.setText("Compra N°");
        panelCompraCrear.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        botonCliente.setBackground(new java.awt.Color(255, 255, 255));
        botonCliente.setForeground(new java.awt.Color(255, 255, 255));
        botonCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/busqueda.png"))); // NOI18N
        botonCliente.setBorder(null);
        botonCliente.setBorderPainted(false);
        botonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClienteActionPerformed(evt);
            }
        });
        panelCompraCrear.add(botonCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 30, 30));

        jLabel7.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel7.setText("Fecha:");
        panelCompraCrear.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jTextField3.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        panelCompraCrear.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 110, 30));

        jLabel9.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel9.setText("Proveedor");
        panelCompraCrear.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel10.setText("Dirección:");
        panelCompraCrear.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, -1, -1));

        jLabel11.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel11.setText("NIT:");
        panelCompraCrear.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        jLabel12.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel12.setText("Nombre:");
        panelCompraCrear.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, -1, -1));

        jLabel13.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel13.setText("Teléfono:");
        panelCompraCrear.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        lblidproveedor.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        lblidproveedor.setText("-");
        panelCompraCrear.add(lblidproveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        lbltelefono.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        lbltelefono.setText("-");
        panelCompraCrear.add(lbltelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 110, -1));

        panelCompra.add(panelCompraCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 910, 400));

        panelCompraTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Compras", "Fecha", "Hora", "Cantidad"
            }
        ));
        tablaCompras.setColorBackgoundHead(new java.awt.Color(64, 132, 253));
        tablaCompras.setColorFilasBackgound2(new java.awt.Color(100, 182, 242));
        tablaCompras.setFont(new java.awt.Font("Decker", 0, 11)); // NOI18N
        tablaCompras.setFuenteHead(new java.awt.Font("Decker", 1, 15)); // NOI18N
        tablaCompras.setGrosorBordeFilas(0);
        tablaCompras.setGrosorBordeHead(0);
        tablaCompras.setRowHeight(20);
        jScrollPane1.setViewportView(tablaCompras);

        panelCompraTabla.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 370));

        panelCompra.add(panelCompraTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 860, 370));

        panelCompraMenu.setBackground(new java.awt.Color(0, 0, 0));
        panelCompraMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonCrear.setBackground(new java.awt.Color(0, 0, 0));
        botonCrear.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        botonCrear.setForeground(new java.awt.Color(255, 255, 255));
        botonCrear.setText("Crear Compra");
        botonCrear.setBorder(null);
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });
        panelCompraMenu.add(botonCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 70));

        botonVer1.setBackground(new java.awt.Color(0, 0, 0));
        botonVer1.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        botonVer1.setForeground(new java.awt.Color(255, 255, 255));
        botonVer1.setText("Ver Compras");
        botonVer1.setBorder(null);
        botonVer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVer1ActionPerformed(evt);
            }
        });
        panelCompraMenu.add(botonVer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 190, 70));

        botonRegresar.setBackground(new java.awt.Color(0, 0, 0));
        botonRegresar.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        botonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        botonRegresar.setText("Regresar");
        botonRegresar.setBorder(null);
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        panelCompraMenu.add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 150, 70));

        panelCompra.add(panelCompraMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 912, -1));

        botonVer.setBackground(new java.awt.Color(0, 0, 0));
        botonVer.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        botonVer.setForeground(new java.awt.Color(255, 255, 255));
        botonVer.setText("Ver Clientes");
        botonVer.setBorder(null);
        botonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerActionPerformed(evt);
            }
        });
        panelCompra.add(botonVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 130, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClienteActionPerformed
        
        vistaCompraProveedorSeleccion vCompraProveedorSeleccion= new vistaCompraProveedorSeleccion(con);

    }//GEN-LAST:event_botonClienteActionPerformed

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        panelCompraCrear.setVisible(true);
        panelCompraTabla.setVisible(false);
        cargarNumCompra();
    }//GEN-LAST:event_botonCrearActionPerformed

    private void botonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerActionPerformed
        //Para poder ver los clientes es necesario poner visible el panel tablaCliente, y el resto invisible
    
    }//GEN-LAST:event_botonVerActionPerformed

    private void botonVer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVer1ActionPerformed
        //Para poder ver los clientes es necesario poner visible el panel tablaCliente, y el resto invisible
        panelCompraCrear.setVisible(false);
        panelCompraTabla.setVisible(true);
        limpiarTabla();
        listar();
    }//GEN-LAST:event_botonVer1ActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdCompraLabel;
    private javax.swing.JButton botonCliente;
    private javax.swing.JButton botonCrear;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JButton botonVer;
    private javax.swing.JButton botonVer1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    public static javax.swing.JLabel lbldireccion;
    public static javax.swing.JLabel lblidproveedor;
    public static javax.swing.JLabel lblproveedornombre;
    public static javax.swing.JLabel lbltelefono;
    private javax.swing.JPanel panelCompra;
    private javax.swing.JPanel panelCompraCrear;
    private javax.swing.JPanel panelCompraMenu;
    private javax.swing.JPanel panelCompraTabla;
    private rojerusan.RSTableMetro tablaCompra;
    private rojerusan.RSTableMetro tablaCompras;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables
}