/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ControlUsuario;
import Modelo.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daniel
 */
public class vistaUsuario extends javax.swing.JFrame {
   
     public void setConexionUsuario(Conexion con1){
       con=con1;
    }
    
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    int id;
    ControlUsuario controlU=new ControlUsuario();/*un objeto control para manejar los usuarios*/
    
    /**
     * Creates new form vistaUsuario
     */
    public vistaUsuario() {
          //this.setUndecorated(true);
          this.setVisible(true);
          initComponents();
          this.setLocationRelativeTo(null);
          listar();
    }
    
    
    /*Este metodo lo que hace es mostrar en una tabla el id de la cuenta, el nombre y la categoria de la cuenta*/
    void listar(){
        modelo=(DefaultTableModel)tablaUsuarios.getModel();
        /*Se almacena la consulta sql en un string*/
    String sql="SELECT * FROM Usuario;";
    try{
       /*se establece coneccion con la base de datos y se le introduce la consulta*/
        cn=con.getConnection();
        st=cn.createStatement();
        rs=st.executeQuery(sql);   
        Object[] Datos= new Object[3]; /*Un array donde se almacenan las filas de la tabla. el tamaño del
        array debe ser el numero de columnas que tenga nuestra consulta*/
        /*modelo=(DefaultTableModel)tablaUsuarios.getModel();*/
        while(rs.next()){
        Datos[0]=rs.getInt("idUsuario");/*deben llamarse exactamente igual a como esta en la tabla*/
        Datos[1]=rs.getString("nombreUsuario");/*deben llamarse exactamente igual a como esta en la tabla*/
        Datos[2]=rs.getString("idCategoCuenta");/*deben llamarse exactamente igual a como esta en la tabla*/
        modelo.addRow(Datos);
        }
        
      /*  modelo.addRow(Datos);
        tablaUsuarios.setModel(modelo);*/
    }catch(SQLException e){}
    }
    
    void limpiarTabla(){
        
        for(int i=0; i<=tablaUsuarios.getRowCount(); i++){
            
            modelo.removeRow(i);
            i=i-1;
        
        }
    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUsuarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        labelTitulo = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        labelCategoria = new javax.swing.JLabel();
        cajaTextoPassword = new javax.swing.JTextField();
        cajaTextoNombre = new javax.swing.JTextField();
        cajaTextoId = new javax.swing.JTextField();
        botonAñadir = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        cajaComboCategoria = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panelUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        panelUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaUsuarios.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idCuenta", "Nombre", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaUsuarios.setFocusable(false);
        tablaUsuarios.setGridColor(new java.awt.Color(153, 153, 153));
        tablaUsuarios.setRowHeight(22);
        tablaUsuarios.getTableHeader().setReorderingAllowed(false);
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaUsuariosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        panelUsuarios.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 740, 270));

        labelTitulo.setFont(new java.awt.Font("Decker", 0, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(102, 102, 102));
        labelTitulo.setText("usuarios");
        panelUsuarios.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 40));

        labelId.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        labelId.setText("ID");
        panelUsuarios.add(labelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        labelNombre.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        labelNombre.setText("Nombre");
        panelUsuarios.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        labelPassword.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        labelPassword.setText("Password");
        panelUsuarios.add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        labelCategoria.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        labelCategoria.setText("Categoria");
        panelUsuarios.add(labelCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));

        cajaTextoPassword.setFont(new java.awt.Font("Quicksand", 0, 18)); // NOI18N
        cajaTextoPassword.setBorder(null);
        cajaTextoPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTextoPasswordActionPerformed(evt);
            }
        });
        panelUsuarios.add(cajaTextoPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 150, 20));

        cajaTextoNombre.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        cajaTextoNombre.setBorder(null);
        panelUsuarios.add(cajaTextoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 150, 20));

        cajaTextoId.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        cajaTextoId.setBorder(null);
        panelUsuarios.add(cajaTextoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 150, 20));

        botonAñadir.setBackground(new java.awt.Color(51, 172, 234));
        botonAñadir.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        botonAñadir.setForeground(new java.awt.Color(255, 255, 255));
        botonAñadir.setText("Añadir");
        botonAñadir.setBorder(null);
        botonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirActionPerformed(evt);
            }
        });
        panelUsuarios.add(botonAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 130, 40));

        botonModificar.setBackground(new java.awt.Color(51, 172, 234));
        botonModificar.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        botonModificar.setForeground(new java.awt.Color(255, 255, 255));
        botonModificar.setText("Modificar");
        botonModificar.setBorder(null);
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });
        panelUsuarios.add(botonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 130, 40));

        botonEliminar.setBackground(new java.awt.Color(51, 172, 234));
        botonEliminar.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminar.setText("Eliminar");
        botonEliminar.setBorder(null);
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        panelUsuarios.add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 130, 40));

        cajaComboCategoria.setBackground(new java.awt.Color(64, 132, 253));
        cajaComboCategoria.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        cajaComboCategoria.setForeground(new java.awt.Color(255, 255, 255));
        cajaComboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Cajero" }));
        panelUsuarios.add(cajaComboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, -1));
        cajaComboCategoria.getAccessibleContext().setAccessibleName("cajaComboCategoria");
        cajaComboCategoria.getAccessibleContext().setAccessibleDescription("");

        panelUsuarios.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 150, 10));
        panelUsuarios.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 150, 10));
        panelUsuarios.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 150, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        try{
            /*se le asignan los atribujos que se ingreso en las cajas de texto a un objeto usuario*/
            controlU.getUsuario().setIdUsuario(Integer.valueOf(cajaTextoId.getText()));
            controlU.eliminar();/*se ejecuta el metodo que agrega una cuenta a la base de datos*/
            limpiarTabla();

        }catch(Exception e){}
        JOptionPane.showMessageDialog(null,"Usuario eliminado con exito");
        listar();// TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        try{
            /*se le asignan los atribujos que se ingreso en las cajas de texto a un objeto usuario*/
            controlU.getUsuario().setIdUsuario(Integer.valueOf(cajaTextoId.getText()));
            controlU.getUsuario().setNombreUsuario(cajaTextoNombre.getText());
            controlU.getUsuario().setPassword(cajaTextoPassword.getText());
            if ("Administrador".equals(String.valueOf(cajaComboCategoria.getSelectedItem()))){
                controlU.getUsuario().setIdCategoCuenta(1);
            }else{
                controlU.getUsuario().setIdCategoCuenta(2);
            }
            controlU.modificar();/*se ejecuta el metodo que agrega una cuenta a la base de datos*/
            limpiarTabla();

        }catch(Exception e){}
        JOptionPane.showMessageDialog(null,"Usuario modificado con exito");
        listar();
        // TODO add your handling code here:
    }//GEN-LAST:event_botonModificarActionPerformed

    private void botonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirActionPerformed
        // TODO add your handling code here:

        try{
            /*se le asignan los atribujos que se ingreso en las cajas de texto a un objeto usuario*/
            controlU.getUsuario().setIdUsuario(Integer.valueOf(cajaTextoId.getText()));
            controlU.getUsuario().setNombreUsuario(cajaTextoNombre.getText());
            controlU.getUsuario().setPassword(cajaTextoPassword.getText());
            if ("Administrador".equals(String.valueOf(cajaComboCategoria.getSelectedItem()))){
                controlU.getUsuario().setIdCategoCuenta(1);
            }else{
                controlU.getUsuario().setIdCategoCuenta(2);
            }
            controlU.agregar();/*se ejecuta el metodo que agrega un usuario a la base de datos*/
            limpiarTabla();

        }catch(Exception e){}
        JOptionPane.showMessageDialog(null,"Usuario registrado con exito");
        listar();
    }//GEN-LAST:event_botonAñadirActionPerformed

    private void cajaTextoPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTextoPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTextoPasswordActionPerformed

    private void tablaUsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMousePressed
        cajaTextoId.setText(String.valueOf(tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 0))); 
        cajaTextoNombre.setText(String.valueOf(tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 1))); 
        if (String.valueOf(tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 2)).equals(String.valueOf(1))){
            cajaComboCategoria.setSelectedIndex(0);
        }else{
            cajaComboCategoria.setSelectedIndex(1);
            }
        cajaTextoPassword.setText(""); 
// TODO add your handling code here:
    }//GEN-LAST:event_tablaUsuariosMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaUsuario().setVisible(true);
            }
        });
    }
    
    private Conexion con;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAñadir;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JComboBox<String> cajaComboCategoria;
    private javax.swing.JTextField cajaTextoId;
    private javax.swing.JTextField cajaTextoNombre;
    private javax.swing.JTextField cajaTextoPassword;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelUsuarios;
    private javax.swing.JTable tablaUsuarios;
    // End of variables declaration//GEN-END:variables
}




