/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import Control.ControlCompras;
import Modelo.Conexion;

/**
 *
 * @author John Castro
 */
public class vistaCompra extends javax.swing.JFrame {

    /**
     * Creates new form vistaCompra
     */
    private Conexion con;
    private ControlCompras controlC;
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    
    public vistaCompra(Conexion con1) {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        con=con1;
    }
    void listar(){    
        modelo=(DefaultTableModel)tablaCompras.getModel();
        /*Se almacena la consulta sql en un string*/
        String sql="SELECT * FROM Compra";
        try{
            /*se establece coneccion con la base de datos y se le introduce la consulta*/
            cn=con.getConnection();
            st=cn.createStatement();
            rs=st.executeQuery(sql);   
            Object[] Datos= new Object[4]; /*Un array donde se almacenan las filas de la tabla. el tamaño del
            array debe ser el numero de columnas que tenga nuestra consulta*/
            while(rs.next()){
            Datos[0]=rs.getInt("idcompra");/*deben llamarse exactamente igual a como esta en la tabla*/
            Datos[1]=rs.getString("idUsuario");/*deben llamarse exactamente igual a como esta en la tabla*/
            Datos[2]=rs.getString("nitproveedor");
            Datos[3]=rs.getString("totalcompra");/*/*deben llamarse exactamente igual a como esta en la tabla*/
            modelo.addRow(Datos);
            }    
        }catch(SQLException e){}
    }
        
    void limpiarTabla(){
        
        modelo=(DefaultTableModel)tablaCompras.getModel();
        while(modelo.getRowCount()>0)modelo.removeRow(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCompra = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelCompraCrear = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        IdCompraLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idproveedortxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCompra = new rojerusan.RSTableMetro();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        proveedornombrelbl = new javax.swing.JLabel();
        panelCompraTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCompras = new rojerusan.RSTableMetro();
        panelCompraMenu = new javax.swing.JPanel();
        botonRegresar = new javax.swing.JToggleButton();
        botonCrear = new javax.swing.JToggleButton();
        botonVer = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelCompra.setBackground(new java.awt.Color(255, 255, 255));
        panelCompra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Decker", 0, 36)); // NOI18N
        jLabel1.setText("Compras");
        panelCompra.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        panelCompraCrear.setBackground(new java.awt.Color(255, 255, 255));
        panelCompraCrear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel3.setText("Número de Factura");
        panelCompraCrear.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jTextField2.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        panelCompraCrear.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 190, 30));

        IdCompraLabel.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        IdCompraLabel.setText("°");
        panelCompraCrear.add(IdCompraLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel5.setText("Proveedor");
        panelCompraCrear.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));

        idproveedortxt.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        idproveedortxt.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                idproveedortxtInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        idproveedortxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idproveedortxtActionPerformed(evt);
            }
        });
        idproveedortxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idproveedortxtKeyTyped(evt);
            }
        });
        panelCompraCrear.add(idproveedortxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 170, 30));

        tablaCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "idArticulo", "Descripcion", "Cantidad", "Costo", "Subtotal"
            }
        ));
        tablaCompra.setFuenteHead(new java.awt.Font("Decker", 1, 18)); // NOI18N
        jScrollPane2.setViewportView(tablaCompra);

        panelCompraCrear.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 910, 250));

        jLabel6.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel6.setText("Número de Compra");
        panelCompraCrear.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelCompraCrear.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 30, -1));

        proveedornombrelbl.setText("jLabel2");
        panelCompraCrear.add(proveedornombrelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, -1));

        panelCompra.add(panelCompraCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 910, 400));

        panelCompraTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Compras", "Fecha", "Hora", "Cantidad"
            }
        ));
        tablaCompras.setColorBackgoundHead(new java.awt.Color(64, 132, 253));
        tablaCompras.setColorFilasBackgound2(new java.awt.Color(100, 182, 242));
        tablaCompras.setFont(new java.awt.Font("Decker", 0, 11)); // NOI18N
        tablaCompras.setFuenteHead(new java.awt.Font("Decker", 1, 15)); // NOI18N
        tablaCompras.setGrosorBordeFilas(0);
        tablaCompras.setGrosorBordeHead(0);
        tablaCompras.setRowHeight(20);
        jScrollPane1.setViewportView(tablaCompras);

        panelCompraTabla.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 370));

        panelCompra.add(panelCompraTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 860, 370));

        panelCompraMenu.setBackground(new java.awt.Color(0, 0, 0));
        panelCompraMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonRegresar.setBackground(new java.awt.Color(0, 0, 0));
        botonRegresar.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        botonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        botonRegresar.setText("Regresar");
        botonRegresar.setBorder(null);
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        panelCompraMenu.add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 190, 70));

        botonCrear.setBackground(new java.awt.Color(0, 0, 0));
        botonCrear.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        botonCrear.setForeground(new java.awt.Color(255, 255, 255));
        botonCrear.setText("Crear Compra");
        botonCrear.setBorder(null);
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });
        panelCompraMenu.add(botonCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 70));

        botonVer.setBackground(new java.awt.Color(0, 0, 0));
        botonVer.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        botonVer.setForeground(new java.awt.Color(255, 255, 255));
        botonVer.setText("Consultar Compra");
        botonVer.setBorder(null);
        botonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerActionPerformed(evt);
            }
        });
        panelCompraMenu.add(botonVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 190, 70));

        panelCompra.add(panelCompraMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 912, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerActionPerformed
        panelCompraCrear.setVisible(false);
        panelCompraTabla.setVisible(true);
        limpiarTabla();
        listar();  
    }//GEN-LAST:event_botonVerActionPerformed

    private void idproveedortxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idproveedortxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idproveedortxtActionPerformed

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        panelCompraCrear.setVisible(true);
        panelCompraTabla.setVisible(false);
                String sql="select max(idcompra)from compra;";
        try{
            /*se establece coneccion con la base de datos y se le introduce la consulta*/
            cn=con.getConnection();
            st=cn.createStatement();
            rs=st.executeQuery(sql);   /*Un array donde se almacenan las filas de la tabla. el tamaño del
            array debe ser el numero de columnas que tenga nuestra consulta*/
            while(rs.next()){
            IdCompraLabel.setText(String.valueOf(rs.getInt(1)+1));
            }    
        }catch(SQLException e){}
    }//GEN-LAST:event_botonCrearActionPerformed

    private void idproveedortxtInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_idproveedortxtInputMethodTextChanged
               // TODO add your handling code here:
    }//GEN-LAST:event_idproveedortxtInputMethodTextChanged

    private void idproveedortxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idproveedortxtKeyTyped
        
    }//GEN-LAST:event_idproveedortxtKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String sql="SELECT nombreproveedor FROM PROVEEDOR WHERE nitproveedor =" +idproveedortxt.getText()+";";
        try{
            /*se establece coneccion con la base de datos y se le introduce la consulta*/
            cn=con.getConnection();
            st=cn.createStatement();
            rs=st.executeQuery(sql);   /*Un array donde se almacenan las filas de la tabla. el tamaño del
            array debe ser el numero de columnas que tenga nuestra consulta*/
            while(rs.next()){
            proveedornombrelbl.setText(rs.getString(1));
            }    
        }catch(SQLException e){}
    }//GEN-LAST:event_jButton1ActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdCompraLabel;
    private javax.swing.JToggleButton botonCrear;
    private javax.swing.JToggleButton botonRegresar;
    private javax.swing.JToggleButton botonVer;
    private javax.swing.JTextField idproveedortxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel panelCompra;
    private javax.swing.JPanel panelCompraCrear;
    private javax.swing.JPanel panelCompraMenu;
    private javax.swing.JPanel panelCompraTabla;
    private javax.swing.JLabel proveedornombrelbl;
    private rojerusan.RSTableMetro tablaCompra;
    private rojerusan.RSTableMetro tablaCompras;
    // End of variables declaration//GEN-END:variables
}
