/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ControlCliente;
import Modelo.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.*;

/**
 *
 * @author Daniel Luna
 */
public class vistaCliente extends javax.swing.JFrame {
    Conexion con=new Conexion();
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    int id;
    ControlCliente controlC=new ControlCliente();/*un objeto control para manejar los clientes*/
    /**
     * Creates new form vistaProvedor
     */
    public vistaCliente() {
        //this.setUndecorated(true);
        this.setVisible(true);
        initComponents();
        this.setLocationRelativeTo(null);
        listar();
    }

        void listar(){
        modelo=(DefaultTableModel)tablaClientes.getModel();
        /*Se almacena la consulta sql en un string*/
        String sql="SELECT * " +
               "FROM Cliente";
    try{
       /*se establece coneccion con la base de datos y se le introduce la consulta*/
        cn=con.getConnection();
        st=cn.createStatement();
        rs=st.executeQuery(sql);   
        Object[] Datos= new Object[4]; /*Un array donde se almacenan las filas de la tabla. el tamaño del
        array debe ser el numero de columnas que tenga nuestra consulta*/
        /*modelo=(DefaultTableModel)tablaUsuarios.getModel();*/
        while(rs.next()){
        Datos[0]=rs.getInt("idcliente");/*deben llamarse exactamente igual a como esta en la tabla*/
        Datos[1]=rs.getString("nombrecliente");/*deben llamarse exactamente igual a como esta en la tabla*/
        Datos[2]=rs.getString("direccioncliente");
        Datos[3]=rs.getString("telefonocliente");/*/*deben llamarse exactamente igual a como esta en la tabla*/
        modelo.addRow(Datos);
        }
        
      /*  modelo.addRow(Datos);
        tablaUsuarios.setModel(modelo);*/
    }catch(SQLException e){}
    }
        
        void limpiarTabla(){
        
        for(int i=0; i<=tablaClientes.getRowCount(); i++){
            
            modelo.removeRow(i);
            i=i-1;
        
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        cajaTextoNit = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        cajaTextoNombre = new javax.swing.JTextField();
        cajaTextoDireccion = new javax.swing.JTextField();
        labelNombre1 = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        cajaTextoTelefono = new javax.swing.JTextField();
        botonAñadir = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Decker", 0, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(102, 102, 102));
        labelTitulo.setText("Clientes");
        jPanel1.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 40));

        labelId.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        labelId.setText("NIT");
        jPanel1.add(labelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        cajaTextoNit.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        cajaTextoNit.setBorder(null);
        jPanel1.add(cajaTextoNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 160, 20));

        labelNombre.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        labelNombre.setText("Nombre");
        jPanel1.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));

        cajaTextoNombre.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        cajaTextoNombre.setBorder(null);
        jPanel1.add(cajaTextoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 160, 20));

        cajaTextoDireccion.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        cajaTextoDireccion.setBorder(null);
        jPanel1.add(cajaTextoDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 160, 20));

        labelNombre1.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        labelNombre1.setText("Dirección");
        jPanel1.add(labelNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, 20));

        labelTelefono.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        labelTelefono.setText("Telefono");
        jPanel1.add(labelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, 20));

        cajaTextoTelefono.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        cajaTextoTelefono.setBorder(null);
        jPanel1.add(cajaTextoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 160, 20));

        botonAñadir.setBackground(new java.awt.Color(51, 172, 234));
        botonAñadir.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        botonAñadir.setForeground(new java.awt.Color(255, 255, 255));
        botonAñadir.setText("Añadir");
        botonAñadir.setBorder(null);
        botonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirActionPerformed(evt);
            }
        });
        jPanel1.add(botonAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 130, 40));

        botonModificar.setBackground(new java.awt.Color(51, 172, 234));
        botonModificar.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        botonModificar.setForeground(new java.awt.Color(255, 255, 255));
        botonModificar.setText("Modificar");
        botonModificar.setBorder(null);
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });
        jPanel1.add(botonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 130, 40));

        botonEliminar.setBackground(new java.awt.Color(51, 172, 234));
        botonEliminar.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminar.setText("Eliminar");
        botonEliminar.setBorder(null);
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 130, 40));

        tablaClientes.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nit", "Nombre", "Dirección", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaClientes.setFocusable(false);
        tablaClientes.setGridColor(new java.awt.Color(153, 153, 153));
        tablaClientes.setRowHeight(22);
        tablaClientes.getTableHeader().setReorderingAllowed(false);
        tablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaClientesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaClientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 740, 320));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 160, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 160, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 160, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 160, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirActionPerformed
        // TODO add your handling code here:

        try{
            /*se le asignan los atribujos que se ingreso en las cajas de texto a un objeto usuario*/
            controlC.getCliente().setIdCliente(Integer.valueOf(cajaTextoNit.getText()));
            controlC.getCliente().setNombre(cajaTextoNombre.getText());
            controlC.getCliente().setTelefono(cajaTextoTelefono.getText());
            controlC.getCliente().setDireccion(cajaTextoDireccion.getText());
            controlC.agregar();/*se ejecuta el metodo que agrega una cuenta a la base de datos*/
            limpiarTabla();

        }catch(Exception e){}
        JOptionPane.showMessageDialog(null,"Cliente registrado con exito");
        listar();
    }//GEN-LAST:event_botonAñadirActionPerformed
    
    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        try{
            /*se le asignan los atribujos que se ingreso en las cajas de texto a un objeto usuario*/
            controlC.getCliente().setIdCliente(Integer.valueOf(cajaTextoNit.getText()));
            controlC.getCliente().setNombre(cajaTextoNombre.getText());
            controlC.getCliente().setTelefono(cajaTextoTelefono.getText());
            controlC.getCliente().setDireccion(cajaTextoDireccion.getText());
            controlC.modificar();/*se ejecuta el metodo que agrega una cuenta a la base de datos*/
            limpiarTabla();

        }catch(Exception e){}
        JOptionPane.showMessageDialog(null,"Cliente modificado con exito");
        listar();
        // TODO add your handling code here:
    }//GEN-LAST:event_botonModificarActionPerformed

    private void tablaClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientesMousePressed
        cajaTextoNit.setText(String.valueOf(tablaClientes.getValueAt(tablaClientes.getSelectedRow(), 0)));
        cajaTextoNombre.setText(String.valueOf(tablaClientes.getValueAt(tablaClientes.getSelectedRow(), 1)));
        cajaTextoDireccion.setText(String.valueOf(tablaClientes.getValueAt(tablaClientes.getSelectedRow(), 2)));
        cajaTextoTelefono.setText(String.valueOf(tablaClientes.getValueAt(tablaClientes.getSelectedRow(), 3)));
    }//GEN-LAST:event_tablaClientesMousePressed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        try{
            /*se le asignan los atribujos que se ingreso en las cajas de texto a un objeto usuario*/
            controlC.getCliente().setIdCliente(Integer.valueOf(cajaTextoNit.getText()));
            controlC.getCliente().setNombre(cajaTextoNombre.getText());
            controlC.getCliente().setTelefono(cajaTextoTelefono.getText());
            controlC.getCliente().setDireccion(cajaTextoDireccion.getText());
            controlC.eliminar();/*se ejecuta el metodo que agrega una cuenta a la base de datos*/
            limpiarTabla();

        }catch(Exception e){}
        JOptionPane.showMessageDialog(null,"Cliente eliminado con exito");
        listar();// TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarActionPerformed
 
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAñadir;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JTextField cajaTextoDireccion;
    private javax.swing.JTextField cajaTextoNit;
    private javax.swing.JTextField cajaTextoNombre;
    private javax.swing.JTextField cajaTextoTelefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombre1;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTable tablaClientes;
    // End of variables declaration//GEN-END:variables
}
