/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ControlProveedor;
import Modelo.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author Daniel Luna
 */
public class vistaProveedor extends javax.swing.JFrame {
    Conexion con=new Conexion();
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    int id;
    ControlProveedor controlP=new ControlProveedor();/*un objeto control para manejar los usuarios*/
    /**
     * Creates new form vistaProvedor
     */
    public vistaProveedor() {
        
        this.setVisible(true);
        initComponents();
        this.setLocationRelativeTo(null);
        listar();
        
    }

        void listar(){
        modelo=(DefaultTableModel)tablaProveedores.getModel();
        /*Se almacena la consulta sql en un string*/
        String sql="SELECT * " +
               "FROM Proveedor";
    try{
       /*se establece coneccion con la base de datos y se le introduce la consulta*/
        cn=con.getConnection();
        st=cn.createStatement();
        rs=st.executeQuery(sql);   
        Object[] Datos= new Object[4]; /*Un array donde se almacenan las filas de la tabla. el tamaño del
        array debe ser el numero de columnas que tenga nuestra consulta*/
        /*modelo=(DefaultTableModel)tablaUsuarios.getModel();*/
        while(rs.next()){
        Datos[0]=rs.getInt("nitproveedor");/*deben llamarse exactamente igual a como esta en la tabla*/
        Datos[1]=rs.getString("nombreprovedor");/*deben llamarse exactamente igual a como esta en la tabla*/
        Datos[2]=rs.getString("direccionproveedor");
        Datos[3]=rs.getString("telefonoproveedor");/*/*deben llamarse exactamente igual a como esta en la tabla*/
        modelo.addRow(Datos);
        }
        
      /*  modelo.addRow(Datos);
        tablaUsuarios.setModel(modelo);*/
    }catch(SQLException e){}
    }
        
        void limpiarTabla(){
        
        for(int i=0; i<=tablaProveedores.getRowCount(); i++){
            
            modelo.removeRow(i);
            i=i-1;
        
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        cajaTextoNit = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        labelNombre1 = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        botonAñadir = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        cajaTextoNombre = new javax.swing.JTextField();
        cajaTextoDireccion = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        cajaTextoTelefono = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Decker", 0, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(102, 102, 102));
        labelTitulo.setText("Proveedores");
        jPanel1.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 19, -1, 40));

        labelId.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        labelId.setText("NIT");
        jPanel1.add(labelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        cajaTextoNit.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        cajaTextoNit.setBorder(null);
        jPanel1.add(cajaTextoNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 210, 20));

        labelNombre.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        labelNombre.setText("Nombre");
        jPanel1.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 17));

        labelNombre1.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        labelNombre1.setText("Dirección");
        jPanel1.add(labelNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        labelTelefono.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        labelTelefono.setText("Telefono");
        jPanel1.add(labelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        botonAñadir.setBackground(new java.awt.Color(51, 172, 234));
        botonAñadir.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        botonAñadir.setForeground(new java.awt.Color(255, 255, 255));
        botonAñadir.setText("Añadir");
        botonAñadir.setBorder(null);
        botonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirActionPerformed(evt);
            }
        });
        jPanel1.add(botonAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 130, 40));

        botonModificar.setBackground(new java.awt.Color(51, 172, 234));
        botonModificar.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        botonModificar.setForeground(new java.awt.Color(255, 255, 255));
        botonModificar.setText("Modificar");
        botonModificar.setBorder(null);
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });
        jPanel1.add(botonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 130, 40));

        botonEliminar.setBackground(new java.awt.Color(51, 172, 234));
        botonEliminar.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminar.setText("Eliminar");
        botonEliminar.setBorder(null);
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 130, 40));

        tablaProveedores.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nit", "Nombre", "Dirección", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProveedores.setFocusable(false);
        tablaProveedores.setGridColor(new java.awt.Color(153, 153, 153));
        tablaProveedores.setRowHeight(22);
        tablaProveedores.getTableHeader().setReorderingAllowed(false);
        tablaProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaProveedoresMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProveedores);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 285, 700, 351));

        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jSeparator1.setMinimumSize(new java.awt.Dimension(1, 1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 206, 10));

        jSeparator2.setAlignmentX(1.0F);
        jSeparator2.setAlignmentY(1.0F);
        jSeparator2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jSeparator2.setMinimumSize(new java.awt.Dimension(1, 1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 206, 10));

        cajaTextoNombre.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        cajaTextoNombre.setBorder(null);
        jPanel1.add(cajaTextoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 210, 20));

        cajaTextoDireccion.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        cajaTextoDireccion.setBorder(null);
        jPanel1.add(cajaTextoDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 210, 20));

        jSeparator3.setAlignmentX(1.0F);
        jSeparator3.setAlignmentY(1.0F);
        jSeparator3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jSeparator3.setMinimumSize(new java.awt.Dimension(1, 1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 206, 10));

        cajaTextoTelefono.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        cajaTextoTelefono.setBorder(null);
        jPanel1.add(cajaTextoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 210, 20));

        jSeparator4.setAlignmentX(1.0F);
        jSeparator4.setAlignmentY(1.0F);
        jSeparator4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jSeparator4.setMinimumSize(new java.awt.Dimension(1, 1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 206, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirActionPerformed
        // TODO add your handling code here:

        try{
            /*se le asignan los atribujos que se ingreso en las cajas de texto a un objeto usuario*/
            controlP.getProveedor().setNit(Integer.valueOf(cajaTextoNit.getText()));
            controlP.getProveedor().setNomProveedor(cajaTextoNombre.getText());
            controlP.getProveedor().setTelefono(cajaTextoTelefono.getText());
            controlP.getProveedor().setDireccion(cajaTextoDireccion.getText());
            controlP.agregar();/*se ejecuta el metodo que agrega una cuenta a la base de datos*/
            limpiarTabla();

        }catch(Exception e){}
        JOptionPane.showMessageDialog(null,"Usario registrado con exito");
        listar();
    }//GEN-LAST:event_botonAñadirActionPerformed
    
    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        try{
            /*se le asignan los atribujos que se ingreso en las cajas de texto a un objeto usuario*/
            controlP.getProveedor().setNit(Integer.valueOf(cajaTextoNit.getText()));
            controlP.getProveedor().setNomProveedor(cajaTextoNombre.getText());
            controlP.getProveedor().setTelefono(cajaTextoTelefono.getText());
            controlP.getProveedor().setDireccion(cajaTextoDireccion.getText());
            controlP.modificar();/*se ejecuta el metodo que agrega una cuenta a la base de datos*/
            limpiarTabla();

        }catch(Exception e){}
        JOptionPane.showMessageDialog(null,"Proveedor modificado con exito");
        listar();
        // TODO add your handling code here:
    }//GEN-LAST:event_botonModificarActionPerformed

    private void tablaProveedoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProveedoresMousePressed
        cajaTextoNit.setText(String.valueOf(tablaProveedores.getValueAt(tablaProveedores.getSelectedRow(), 0)));
        cajaTextoNombre.setText(String.valueOf(tablaProveedores.getValueAt(tablaProveedores.getSelectedRow(), 1)));
        cajaTextoDireccion.setText(String.valueOf(tablaProveedores.getValueAt(tablaProveedores.getSelectedRow(), 2)));
        cajaTextoTelefono.setText(String.valueOf(tablaProveedores.getValueAt(tablaProveedores.getSelectedRow(), 3)));
    }//GEN-LAST:event_tablaProveedoresMousePressed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        try{
            /*se le asignan los atribujos que se ingreso en las cajas de texto a un objeto usuario*/
            controlP.getProveedor().setNit(Integer.valueOf(cajaTextoNit.getText()));
            controlP.getProveedor().setNomProveedor(cajaTextoNombre.getText());
            controlP.getProveedor().setTelefono(cajaTextoTelefono.getText());
            controlP.getProveedor().setDireccion(cajaTextoDireccion.getText());
            controlP.eliminar();/*se ejecuta el metodo que agrega una cuenta a la base de datos*/
            limpiarTabla();

        }catch(Exception e){}
        JOptionPane.showMessageDialog(null,"Proveedor eliminado con exito");
        listar();// TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarActionPerformed
 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAñadir;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JTextField cajaTextoDireccion;
    private javax.swing.JTextField cajaTextoNit;
    private javax.swing.JTextField cajaTextoNombre;
    private javax.swing.JTextField cajaTextoTelefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombre1;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTable tablaProveedores;
    // End of variables declaration//GEN-END:variables
}
